# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '单个Cell设置圆角背景' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 单个Cell设置圆角背景

  pod 'SnapKit'

end
